// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE5F0wT2JQKB4Ystj4cjbLD4rIiu2zeCY',
    appId: '1:309790480915:web:84e3a731bd2d11212afde6',
    messagingSenderId: '309790480915',
    projectId: 'project-b33800ca-80c2-4845-a02',
    authDomain: 'project-b33800ca-80c2-4845-a02.firebaseapp.com',
    storageBucket: 'project-b33800ca-80c2-4845-a02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuhZ6xjT3uqpG_ML5mHPyo489dncVJ2QI',
    appId: '1:309790480915:android:557648450e296d7b2afde6',
    messagingSenderId: '309790480915',
    projectId: 'project-b33800ca-80c2-4845-a02',
    storageBucket: 'project-b33800ca-80c2-4845-a02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPdw3hp8JcPGv1OrY6f9GsPqxkzx6XMWo',
    appId: '1:309790480915:ios:e36f7eb8c849ce0a2afde6',
    messagingSenderId: '309790480915',
    projectId: 'project-b33800ca-80c2-4845-a02',
    storageBucket: 'project-b33800ca-80c2-4845-a02.firebasestorage.app',
    iosBundleId: 'com.example.fireDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPdw3hp8JcPGv1OrY6f9GsPqxkzx6XMWo',
    appId: '1:309790480915:ios:e36f7eb8c849ce0a2afde6',
    messagingSenderId: '309790480915',
    projectId: 'project-b33800ca-80c2-4845-a02',
    storageBucket: 'project-b33800ca-80c2-4845-a02.firebasestorage.app',
    iosBundleId: 'com.example.fireDemo',
  );
}
